name: 微信登陆插件
identification: notadd/wechat-login
description: 微信登陆插件的配置和管理。
author:
    - twilroad
    - 269044570@qq.com
version: 0.1.0
provider: Notadd\WechatLogin\Extension
assets:
    scripts:
        - assets/extensions/notadd/wechat-login/js/extension.min.js
    stylesheets:
        - assets/extensions/notadd/wechat-login/css/extension.min.css
events:
    subscribes:
        - Notadd\WechatLogin\Listeners\CsrfTokenRegister
        - Notadd\WechatLogin\Listeners\RouteRegister
